### ISSUE TITLE
Follow tutorial: http://nicolashery.com/parse-data-files-using-nodejs-streams/

### ISSUE THREAD

**Issue by kenpeter** [nicolashery/example-stream-parser#1]
// ./parer === https://github.com/nicolashery/example-stream-parser/blob/master/lib/parser.js
var myparser = require('./parser');

var Transform = require('stream').Transform
  , csv = require('csv-streamify')
  , JSONStream = require('JSONStream');

var csvToJson = csv({objectMode: true});

var jsonToStrings = JSONStream.stringify(false);

process.stdin
.pipe(csvToJson)
.pipe(myparser)
.pipe(jsonToStrings)
.pipe(process.stdout);

// How I run it
// cat test_data.txt | node script.js
// script.js is this script. test_data.txt is the csv data in http://nicolashery.com/parse-data-files-using-nodejs-streams/

// Error
/*
/home/kenpeter/.nvm/versions/node/v0.12.4/lib/node_modules/csv-streamify/node_modules/readable-stream/lib/_stream_readable.js:527
  dest.on('unpipe', onunpipe);
       ^
TypeError: undefined is not a function
    at CSVStream.Readable.pipe (/home/kenpeter/.nvm/versions/node/v0.12.4/lib/node_modules/csv-streamify/node_modules/readable-stream/lib/_stream_readable.js:527:8)
    at Object.<anonymous> (/var/www/html/test/testme/store_guide/test/script.js:16:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
*/

**Comment by nicolashery** [comment]
`lib/parser.js` actually exports a function taking an `options` object and returning a new transform stream (similar to `csv-streamify` and `JSONStream`).

Try this:

``` javascript
var myparser = require('./parser');
var csv = require('csv-streamify');
var JSONStream = require('JSONStream');

var csvToJson = csv({objectMode: true});
var parse = myparser(); // added
var jsonToStrings = JSONStream.stringify(false);

process.stdin
.pipe(csvToJson)
.pipe(parse) // changed
.pipe(jsonToStrings)
.pipe(process.stdout);
```
